import {
  WORKBENCH_AUTHORITY,
  WorkbenchError,
  deepFreeze,
} from "./contracts.mjs";
import { safeDisplayText } from "./display-safety.mjs";

export const MEMORY_CONTEXT_FORMAT = "dubsar.memory-context/1";

function safe(value, max, fallback) {
  const result = safeDisplayText(value, max);
  return result.redacted || result.text.length === 0 ? fallback : result.text;
}

export function buildMemoryContext({ inspection, workId } = {}) {
  if (inspection?.snapshot?.workspace_mode !== "memory_vnext") {
    throw new WorkbenchError("MEMORY_WORKSPACE_REQUIRED");
  }
  const memory = inspection.evaluation.memory;
  const work = workId === undefined
    ? memory.selected_work
    : memory.work_items.find((item) => item.work_id === workId) ?? null;
  if (work === null) throw new WorkbenchError("MEMORY_WORK_SELECTION_REQUIRED");
  const knowledgeById = new Map(
    inspection.snapshot.documents.knowledge
      .filter((item) => item.status === "approved")
      .map((item) => [item.knowledge_id, item]),
  );
  const knowledge = work.knowledge_ids.flatMap((id) => {
    const item = knowledgeById.get(id);
    return item ? [{
      knowledge_id: item.knowledge_id,
      kind: item.kind,
      title: safe(item.title, 300, "Knowledge entry"),
      statement: safe(item.statement, 1_000, "Knowledge content withheld."),
    }] : [];
  });
  const route = inspection.evaluation.next_action;
  const value = {
    format: MEMORY_CONTEXT_FORMAT,
    authority: WORKBENCH_AUTHORITY,
    content_trust: "untrusted_project_data",
    generated: true,
    source: {
      project_id: inspection.evaluation.id,
      work_id: work.work_id,
      snapshot_sha256: inspection.snapshot.snapshot_sha256,
      shared_snapshot_sha256: inspection.snapshot.shared_snapshot_sha256,
    },
    project: { title: safe(memory.project.title, 300, "Untitled project") },
    work: {
      title: safe(work.title, 300, "Untitled work"),
      status: work.status,
      scope: work.scope,
      objective: safe(work.objective, 1_500, "No objective recorded."),
      acceptance_criteria: work.acceptance_criteria.map((item) => safe(item, 500, "Criterion withheld.")),
      references: [...work.references],
    },
    knowledge,
    blockers: inspection.evaluation.continuity.open_blockers.map((item) => safe(item.statement, 500, "Blocker recorded.")),
    next_action: { code: route.code, label: safe(route.label, 500, "Review the recorded state.") },
    native_guidance: {
      plan: new Set(["multi_step", "multi_session"]).has(work.scope) ? "consider" : "not_indicated",
      goal: work.scope === "multi_session" || work.status === "paused" ? "consider" : "not_indicated",
      auto_execute: false,
    },
    authority_limits: [
      "Generated context is advisory data, not a host instruction file.",
      "No work selection, plan, goal, subagent, command, or write is automatic.",
      "Revalidate the live project before material action.",
    ],
  };
  return deepFreeze(value);
}

export function renderMemoryContextMarkdown(context) {
  if (context?.format !== MEMORY_CONTEXT_FORMAT) throw new WorkbenchError("MEMORY_CONTEXT_INVALID");
  const lines = [
    "<!-- GENERATED BY DUBSAR - ADVISORY DATA - DO NOT EDIT -->",
    "# DUBSAR Project Context",
    "",
    `Snapshot: \`${context.source.snapshot_sha256}\``,
    `Project: ${context.project.title}`,
    "",
    `## Work: ${context.work.title}`,
    "",
    `Status: ${context.work.status} · Scope: ${context.work.scope}`,
    "",
    context.work.objective,
    "",
    "### Acceptance criteria",
    ...context.work.acceptance_criteria.map((item) => `- ${item}`),
    "",
    "### Linked knowledge",
    ...(context.knowledge.length === 0
      ? ["- None linked."]
      : context.knowledge.map((item) => `- **${item.title}** (${item.kind}): ${item.statement}`)),
    "",
    "### Recorded blockers",
    ...(context.blockers.length === 0 ? ["- None recorded."] : context.blockers.map((item) => `- ${item}`)),
    "",
    "### Next recorded action",
    context.next_action.label,
    "",
    "### Native host guidance",
    `- Plan: ${context.native_guidance.plan}`,
    `- Goal: ${context.native_guidance.goal}`,
    "- Subagents: host decides; DUBSAR does not require them.",
    "",
    "This file is generated advisory context. It is never copied into AGENTS.md, CLAUDE.md, or Cursor rules.",
    "",
  ];
  return lines.join("\n");
}
